import {
  Gift,
  Trophy,
  Rocket,
  Gem,
  Wallet,
  Image,
  Coins,
  Building2,
  Building,
  Landmark,
  Blocks,
  Box,
  Handshake,
  Wrench,
  RefreshCw,
  ScrollText,
  FileText,
  Flame,
  Timer,
  Star,
  Heart,
  Check,
  X,
  AlertCircle,
  Info,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  Plus,
  Minus,
  Edit,
  Trash2,
  Settings,
  Search,
  Filter,
  Download,
  Upload,
  Copy,
  Share2,
  ExternalLink,
  Link,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Shield,
  ShieldCheck,
  ShieldAlert,
  User,
  Users,
  UserCheck,
  UserPlus,
  UserMinus,
  Mail,
  Phone,
  MessageCircle,
  MessageSquare,
  Send,
  Bell,
  BellRing,
  Home,
  Store,
  ShoppingCart,
  ShoppingBag,
  Archive,
  Folder,
  File,
  FileCode,
  FileImage,
  Calendar,
  Clock,
  History,
  RotateCw,
  Loader2,
  Play,
  Pause,
  StopCircle,
  FastForward,
  Rewind,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  Video,
  VideoOff,
  Monitor,
  Smartphone,
  Laptop,
  Package,
  FolderOpen,
  Type,
  DollarSign,
  Ticket,
  Vote,
  Thermometer,
  Banknote,
  Briefcase,
  Plug,
  Bot,
  Music,
  Tag,
  Cpu,
  HardDrive,
  Server,
  Database,
  Network,
  CircleDot,
  Grid3x3 as Grid,
  Layers,
  Circle,
  Diamond,
  Cloud,
  CloudDownload,
  CloudUpload,
  Wifi,
  WifiOff,
  Globe,
  Map,
  MapPin,
  Navigation,
  Compass,
  Target,
  Award,
  Medal,
  Crown,
  Sparkles,
  Zap,
  Sun,
  Moon,
  CloudRain,
  CloudSnow,
  Wind,
  Droplet,
  Umbrella,
  Coffee,
  Pizza,
  Apple,
  Cherry,
  Grape,
  Carrot,
  Cookie,
  Cake,
  Beer,
  Wine,
  Milk,
  Sandwich,
  Soup,
  Fish,
  Egg,
  Candy,
  Brain,
  Smile,
  Frown,
  Meh,
  ThumbsUp,
  ThumbsDown,
  Hand,
  Fingerprint,
  Activity,
  Anchor,
  BookOpen,
  Book,
  Bookmark,
  Calculator,
  Cast,
  CheckCircle,
  CheckSquare,
  CircleEllipsis,
  CircleSlash,
  Clipboard,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardX,
  Code,
  Code2,
  Command,
  CreditCard,
  Crop,
  Crosshair,
  Disc,
  Euro,
  Feather,
  Flag,
  Framer,
  Gamepad2,
  Ghost,
  GitBranch,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Github,
  Gitlab,
  GraduationCap,
  Grid3x3,
  Hash,
  Headphones,
  HelpCircle,
  Hexagon,
  Highlighter,
  Inbox,
  Infinity,
  Instagram,
  Layout,
  LifeBuoy,
  Link2,
  Linkedin,
  List,
  ListOrdered,
  Loader,
  LogIn,
  LogOut,
  Maximize,
  Maximize2,
  Menu,
  Minimize,
  Minimize2,
  MoreHorizontal,
  MoreVertical,
  Mountain,
  Move,
  Octagon,
  Palette,
  Paperclip,
  PenTool,
  Percent,
  PersonStanding,
  PieChart,
  Pin,
  PlusCircle,
  PlusSquare,
  Pocket,
  Power,
  Printer,
  QrCode,
  Radio,
  Receipt,
  RectangleHorizontal,
  RectangleVertical,
  Repeat,
  Reply,
  Rss,
  Save,
  Scale,
  Scan,
  Scissors,
  SeparatorHorizontal,
  SeparatorVertical,
  Settings2,
  Share,
  Shuffle,
  SidebarClose,
  SidebarOpen,
  Signal,
  Slash,
  Sliders,
  Sparkle,
  Square,
  SquareDot,
  StickyNote,
  Sunrise,
  Sunset,
  Table,
  Tablet,
  Tags,
  Terminal,
  TestTube,
  TestTube2,
  TextCursor,
  ToggleLeft,
  ToggleRight,
  Trash,
  TreePine,
  TrendingDown,
  TrendingUp,
  Triangle,
  Truck,
  Tv,
  Twitter,
  Underline,
  Undo,
  Unlink,
  UserX,
  Voicemail,
  Volume,
  Watch,
  Waves,
  Webcam,
  Youtube,
  ZoomIn,
  ZoomOut,
  AlertTriangle,
  type LucideIcon
} from 'lucide-react';

// Comprehensive emoji to Lucide icon mapping
export const emojiToLucideMap: Record<string, LucideIcon> = {
  // Gift & Rewards
  '🎁': Gift,
  
  // Geometric symbols to Lucide mappings for curriculum
  '⚙': Settings,      // Protocol & Computing
  '◆': TrendingUp,    // Assets & Markets  
  '▲': Users,          // Organization & Economic Design
  '◐': Network,        // Infrastructure & Interop
  '♦': Shield,         // Security & Compliance
  '▼': Database,       // Data & Storage
  '▪': Box,            // Generic module
  '◉': Circle,         // Lesson indicator
  '◪': Square,         // Unit indicator
  '◫': Layers,         // Stack layers
  '◈': Diamond,        // Special feature
  '◇': Code,           // Code lesson
  '▣': Grid,           // Grid layout
  '◒': CircleDot,      // Progress indicator
  '★': Star,           // Featured content
  '✓': Check,          // Completed
  
  // Specific module emojis - Perfect icon matches
  '👛': Wallet,       // Wallet Master
  '🦊': Code,         // Fox -> Code/Dev
  '🏦': Building2,    // Banking/Finance
  '💎': Gem,          // Diamond/Value
  '🔧': Wrench,       // Tools/Build
  '🤝': Handshake,    // Partnership/Consensus
  '📈': TrendingUp,   // Growth/Analytics
  '🌐': Globe,        // Global/Network
  '📚': BookOpen,     // Learning/Education
  '🔐': Lock,         // Security/Lock
  '📝': FileText,     // Documentation
  '🔄': RefreshCw,    // Cycle/Refresh
  '🔑': Key,          // Keys/Access
  '💾': HardDrive,    // Storage/Data
  '🧱': Blocks,       // Building blocks
  '🏗️': Building,     // Architecture
  '🏛️': Landmark,     // Government/DAO
  '📜': ScrollText,   // Smart Contract
  '🎣': Target,       // Phishing/Hooks
  '🧹': Sparkles,     // Clean/Sweep
  '👥': Users,        // Community/People
  '📦': Package,      // Package/Box
  '🗂️': FolderOpen,   // Files/Organization
  '🖥️': Monitor,      // Computer/Desktop
  '🔤': Type,         // Text/Typography
  '🏪': Store,        // Marketplace/Store
  '🖼️': Image,        // NFT/Image
  '💵': DollarSign,   // Money/USD
  '🌉': Landmark,     // Bridge/Connection
  '👑': Crown,        // Premium/Luxury
  '🔥': Flame,        // Hot/Fire
  '🎫': Ticket,       // Ticket/Event
  '🗳️': Vote,         // Voting/Governance
  '🌡️': Thermometer,  // Temperature/Metrics
  '🔰': ShieldAlert,  // Warning/Security
  '💸': Banknote,     // Money flow
  '💼': Briefcase,    // Business/Portfolio
  '🔗': Link,         // Connection/Link
  '🛡️': Shield,       // Shield/Protection
  '🔌': Plug,         // Plugin/Connect
  '📤': Upload,       // Upload/Export
  '📡': Wifi,         // Network/Signal
  '🤖': Bot,          // AI/Robot
  '🎵': Music,        // Music/Audio
  '🏷️': Tag,          // Label/Tag
  
  '🎉': Sparkles,
  '🎊': Sparkles,
  '🏆': Trophy,
  '🥇': Medal,
  '🥈': Medal,
  '🥉': Medal,
  '💶': Euro,
  '🪙': Coins,
  
  // Navigation & Actions
  '🚀': Rocket,
  '✈️': Send,
  '➡️': ArrowRight,
  '⬅️': ArrowLeft,
  '⬆️': ArrowUp,
  '⬇️': ArrowDown,
  '↗️': ArrowRight,
  '↖️': ArrowLeft,
  '↘️': ArrowRight,
  '↙️': ArrowLeft,
  '🔃': RotateCw,
  '⏮️': Rewind,
  '⏭️': FastForward,
  '⏯️': Play,
  '⏸️': Pause,
  '⏹️': StopCircle,
  
  // Status & Feedback
  '✅': CheckCircle,
  '✔️': Check,
  '❌': X,
  '❗': AlertCircle,
  '❓': HelpCircle,
  '⚠️': AlertTriangle,
  '⚡': Zap,
  '✨': Sparkles,
  '⭐': Star,
  '🌟': Star,
  '💫': Sparkles,
  
  // Wallet & Finance
  '💳': CreditCard,
  '🛒': ShoppingCart,
  '🛍️': ShoppingBag,
  
  // Files & Media
  '📷': Camera,
  '📸': Camera,
  '🎥': Video,
  '📹': Video,
  '🎬': Video,
  '🎭': Palette,
  '🎨': Palette,
  '📁': Folder,
  '📂': FolderOpen,
  '📄': FileText,
  '📃': File,
  '📋': Clipboard,
  '📊': PieChart,
  '📉': TrendingDown,
  
  // Communication
  '💬': MessageCircle,
  '💭': MessageSquare,
  '🗨️': MessageCircle,
  '📢': Bell,
  '🔔': Bell,
  '🔕': BellRing,
  '📧': Mail,
  '✉️': Mail,
  '📞': Phone,
  '📱': Smartphone,
  
  // Security & Privacy
  '🔒': Lock,
  '🔓': Unlock,
  '⚔️': ShieldAlert,
  
  // Time & Date
  '⏰': Clock,
  '⏱️': Timer,
  '⏲️': Timer,
  '🕐': Clock,
  '📅': Calendar,
  '📆': Calendar,
  '🗓️': Calendar,
  
  // Education & Learning
  '📖': Book,
  '📕': Book,
  '📗': Book,
  '📘': Book,
  '📙': Book,
  '🎓': GraduationCap,
  '✏️': PenTool,
  '🖊️': PenTool,
  '🖋️': Feather,
  
  // Technology
  '💻': Laptop,
  '⌨️': Terminal,
  '🖱️': Crosshair,
  '💿': Disc,
  '📀': Disc,
  '🔋': Activity,
  '📶': Signal,
  '📳': Smartphone,
  
  // People & Emotions
  '👤': User,
  '👨': User,
  '👩': User,
  '👦': User,
  '👧': User,
  '😀': Smile,
  '😃': Smile,
  '😄': Smile,
  '😁': Smile,
  '😆': Smile,
  '😅': Smile,
  '😂': Smile,
  '🙂': Smile,
  '😊': Smile,
  '😇': Smile,
  '😢': Frown,
  '😭': Frown,
  '😐': Meh,
  '😑': Meh,
  '👍': ThumbsUp,
  '👎': ThumbsDown,
  '👏': Handshake,
  '🙏': Hand,
  '❤️': Heart,
  '💙': Heart,
  '💚': Heart,
  '💛': Heart,
  '💜': Heart,
  '🖤': Heart,
  '🤍': Heart,
  '💔': Heart,
  
  // Nature & Weather
  '☀️': Sun,
  '🌞': Sun,
  '🌙': Moon,
  '🌛': Moon,
  '🌜': Moon,
  '☁️': Cloud,
  '🌧️': CloudRain,
  '⛈️': CloudRain,
  '🌩️': Zap,
  '🌨️': CloudSnow,
  '❄️': CloudSnow,
  '☃️': CloudSnow,
  '🌬️': Wind,
  '💨': Wind,
  '💧': Droplet,
  '💦': Droplet,
  '☔': Umbrella,
  '🌊': Waves,
  '🏔️': Mountain,
  '🌲': TreePine,
  '🌳': TreePine,
  
  // Tools & Settings
  '🔨': Settings2,
  '⚙️': Settings,
  '🛠️': Settings2,
  '⚒️': Settings2,
  '🔍': Search,
  '🔎': Search,
  '🔦': Search,
  '🔭': Search,
  '🔬': TestTube2,
  '🧪': TestTube,
  '⚗️': TestTube2,
  '🗑️': Trash2,
  '✂️': Scissors,
  '📌': Pin,
  '📍': MapPin,
  '🏴': Flag,
  '🏳️': Flag,
  '🚩': Flag,
  
  // Miscellaneous
  '🌍': Globe,
  '🌎': Globe,
  '🌏': Globe,
  '🗺️': Map,
  '🧭': Compass,
  '🎯': Target,
  '🎲': Gamepad2,
  '🎮': Gamepad2,
  '🎪': Mountain,
  '🎡': Circle,
  '🎢': TrendingUp,
  '🎠': Mountain,
  '🎟️': Ticket,
  '🏠': Home,
  '🏡': Home,
  '🏢': Building,
  '🏬': Store,
  '🏭': Building2,
  '🚪': RectangleVertical,
  '🪟': RectangleHorizontal,
  '🛏️': RectangleHorizontal,
  '🪑': Square,
  '🍔': Sandwich,
  '🍕': Pizza,
  '🍎': Apple,
  '🍒': Cherry,
  '🍇': Grape,
  '🥕': Carrot,
  '🍪': Cookie,
  '🎂': Cake,
  '🍺': Beer,
  '🍷': Wine,
  '🥛': Milk,
  '🍲': Soup,
  '🐟': Fish,
  '🥚': Egg,
  '🍬': Candy,
  '☕': Coffee,
  '🧠': Brain,
  '👻': Ghost,
  '👾': Gamepad2,
  '🚦': Activity,
  '⚓': Anchor,
  '🎸': Music,
  '🎶': Music,
  '🎼': Music,
  '🎤': Mic,
  '🎧': Headphones,
  '📻': Radio,
  '📺': Tv,
  '📽️': Video,
  '🎞️': Video,
  '🖨️': Printer,
  '⌚': Watch,
  '⏳': Timer,
  '⌛': Timer,
  '📏': SeparatorHorizontal,
  '📐': Triangle,
  '🖌️': Palette,
  '🖍️': Highlighter,
  '📎': Paperclip,
  '⛓️': Link,
  '🧲': Anchor,
  '💡': LifeBuoy,
  '🌅': Sunrise,
  '🌄': Sunset,
  '🌠': Sparkles,
  '🎆': Sparkles,
  '🎇': Sparkles,
  '🌈': Palette,
  '🌂': Umbrella,
  '☂️': Umbrella,
  '⛄': CloudSnow,
  '🌪️': Wind,
  '🌫️': Cloud,
  '💥': Zap,
  '🌋': Mountain,
  '🗻': Mountain,
  '⛰️': Mountain,
  '🗿': Square,
  '🗽': Building2,
  '🗼': Building2,
  '⛲': Droplet,
  '⛺': Mountain,
  '🏕️': Mountain,
  '🏖️': Waves,
  '🏜️': Mountain,
  '🏝️': Mountain,
  '🏞️': Mountain,
  '🚥': Activity,
  '🚧': AlertTriangle,
  '⛔': CircleSlash,
  '🛑': Octagon,
  '☢️': AlertTriangle,
  '☣️': AlertTriangle,
  '↕️': SeparatorVertical,
  '↔️': SeparatorHorizontal,
  '↩️': Reply,
  '↪️': Reply,
  '⤴️': ArrowUp,
  '⤵️': ArrowDown,
  '🔀': Shuffle,
  '🔁': Repeat,
  '🔂': Repeat,
  '▶️': Play,
  '◀️': ArrowLeft,
  '🔼': ChevronUp,
  '⏫': ChevronUp,
  '🔽': ChevronDown,
  '⏬': ChevronDown,
  '⏺️': Circle,
  '⏏️': Upload,
  '🔇': VolumeX,
  '🔈': Volume,
  '🔉': Volume2,
  '🔊': Volume2,
  '📣': Bell,
  '📯': Bell,
  '♻️': RefreshCw,
  '🔱': Target,
  '📛': Tag,
  '⭕': Circle,
  '☑️': CheckSquare,
  '❎': X,
  '➕': Plus,
  '➖': Minus,
  '➗': Slash,
  '✖️': X,
  '♾️': Infinity,
  '💲': DollarSign,
  '💱': DollarSign,
  '™️': Circle,
  '©️': Circle,
  '®️': Circle,
  '‼️': AlertCircle,
  '⁉️': HelpCircle,
  '❔': HelpCircle,
  '❕': AlertCircle,
  '〰️': Waves,
  '💤': Meh,
  '🅰️': Type,
  '🆎': Type,
  '🅱️': Type,
  '🆑': Type,
  '🆒': Type,
  '🆓': Type,
  'ℹ️': Info,
  '🆔': CreditCard,
  'Ⓜ️': Circle,
  '🆕': PlusCircle,
  '🆖': X,
  '🅾️': Circle,
  '🆗': CheckCircle,
  '🅿️': Square,
  '🆘': AlertTriangle,
  '🆙': TrendingUp,
  '🆚': Zap,
  '🔴': Circle,
  '🟠': Circle,
  '🟡': Circle,
  '🟢': Circle,
  '🔵': Circle,
  '🟣': Circle,
  '🟤': Circle,
  '⚫': Circle,
  '⚪': Circle,
  '🟥': Square,
  '🟧': Square,
  '🟨': Square,
  '🟩': Square,
  '🟦': Square,
  '🟪': Square,
  '🟫': Square,
  '⬛': Square,
  '⬜': Square,
  '◼️': SquareDot,
  '◻️': Square,
  '◾': SquareDot,
  '◽': Square,
  '▪️': SquareDot,
  '▫️': Square,
  '🔶': Hexagon,
  '🔷': Hexagon,
  '🔸': Triangle,
  '🔹': Triangle,
  '🔺': Triangle,
  '🔻': Triangle,
  '💠': Hexagon,
  '🔘': CircleDot,
  '🔳': Square,
  '🔲': SquareDot,
};

// Default icon for unmapped emojis
export const defaultIcon = HelpCircle;

// Helper function to get Lucide icon for an emoji
export function getLucideIconForEmoji(emoji: string): LucideIcon {
  return emojiToLucideMap[emoji] || defaultIcon;
}

// Helper to check if a string contains emojis
export function containsEmoji(text: string): boolean {
  // Check if the text is in our mapping
  return Object.keys(emojiToLucideMap).some(emoji => text.includes(emoji));
}

// Helper to extract emojis from text
export function extractEmojis(text: string): string[] {
  const emojis: string[] = [];
  Object.keys(emojiToLucideMap).forEach(emoji => {
    if (text.includes(emoji)) {
      emojis.push(emoji);
    }
  });
  return emojis;
}

// Helper to replace emojis in text with icon placeholders
export function replaceEmojisWithPlaceholders(text: string): { text: string; emojis: string[] } {
  const emojis = extractEmojis(text);
  let processedText = text;
  
  emojis.forEach((emoji, index) => {
    processedText = processedText.replace(emoji, `__ICON_${index}__`);
  });
  
  return { text: processedText, emojis };
}